name: ExampleApp
options:
  bundleIdPrefix: com.arclabs.arcnavigation
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "6.0"
    ENABLE_USER_SCRIPT_SANDBOXING: false
    SWIFT_STRICT_CONCURRENCY: complete

packages:
  ARCNavigation:
    path: ../..

targets:
  ExampleApp:
    type: application
    platform: iOS
    sources:
      - ExampleApp
    dependencies:
      - package: ARCNavigation
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        PRODUCT_BUNDLE_IDENTIFIER: com.arclabs.arcnavigation.example
        PRODUCT_NAME: "$(TARGET_NAME)"
        GENERATE_INFOPLIST_FILE: true
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: 1.0.0
